# Generated by Django 4.0.4 on 2022-05-25 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakeUpTime', models.CharField(max_length=10)),
                ('sleepTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.CharField(max_length=30)),
                ('physics', models.CharField(max_length=30)),
                ('history', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('numberOfTest', models.IntegerField(max_length=1000)),
                ('qualityOfStudy', models.IntegerField(max_length=5)),
                ('dailyReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gozareshyarbot.dailyreport')),
                ('subject', models.ManyToManyField(to='gozareshyarbot.subject')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gozareshyarbot.student'),
        ),
    ]
