# Generated by Django 4.0.4 on 2022-05-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0002_remove_studytask_dailyreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='userId',
            new_name='user_id',
        ),
    ]
