# Generated by Django 4.0.4 on 2022-05-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0003_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakeUpTime', models.CharField(max_length=10)),
                ('sleepTime', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gozareshyarbot.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=10)),
                ('numberOfTest', models.IntegerField()),
                ('qualityOfStudy', models.IntegerField()),
                ('dailyReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gozareshyarbot.dailyreport')),
            ],
        ),
    ]
