# Generated by Django 4.0.4 on 2022-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0007_alter_student_phone_number_alter_student_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='sleepTime',
            new_name='sleep_time',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='wakeUpTime',
            new_name='wake_up_time',
        ),
        migrations.RenameField(
            model_name='studytask',
            old_name='dailyReport',
            new_name='daily_report',
        ),
        migrations.RenameField(
            model_name='studytask',
            old_name='numberOfTest',
            new_name='number_of_test',
        ),
        migrations.RenameField(
            model_name='studytask',
            old_name='qualityOfStudy',
            new_name='quality_of_study',
        ),
    ]
