# Generated by Django 4.0.4 on 2022-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0010_alter_dailyreport_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='number_of_test',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='quality_of_study',
            field=models.IntegerField(null=True),
        ),
    ]
