# Generated by Django 4.0.4 on 2022-05-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0011_alter_studytask_number_of_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
