# Generated by Django 4.0.4 on 2022-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0012_alter_studytask_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
