# Generated by Django 4.0.4 on 2022-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gozareshyarbot', '0015_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='message_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
